// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficLightAPI.Context;

namespace TrafficLightAPI.Migrations
{
    [DbContext(typeof(TrafficLightContext))]
    [Migration("20210117142703_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TrafficLightAPI.Models.Observation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumbersStr")
                        .HasColumnType("TEXT");

                    b.Property<string>("SequenceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SequenceId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("TrafficLightAPI.Models.Sequence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokenNumbersStr")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CatheringDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOver")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxClock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NickedBrokenNumbersStr")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartClock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartClocksStr")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartColor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("TrafficLightAPI.Models.Observation", b =>
                {
                    b.HasOne("TrafficLightAPI.Models.Sequence", "Sequence")
                        .WithMany()
                        .HasForeignKey("SequenceId");

                    b.Navigation("Sequence");
                });
#pragma warning restore 612, 618
        }
    }
}
